pluginName: "SIGCSE 2025"
pluginDescription: "We want to track your progress through the course in order to collect data on file changes during the course completion. Please, when you are ready, press the next button."
researchId: "SIGCSE2025"