surveys:
  - id: default
    htmlQuestions:
      - !<Radio>
        text: Single choice question
        elementId: single
        required: true
        info:
          - id: single1
            value: 1
          - id: single2
            value: 2
          - id: single3
            value: 3
      - !<Checkbox>
        text: Multichoice question
        elementId: multichoice
        required: true
        info:
          - id: multichoice1
            value: 1
          - id: multichoice2
            value: 2
          - id: multichoice3
            value: 3
      - !<Input>
        text: Input question
        elementId: input
      - !<Textarea>
        text: Textarea question
        elementId: textarea
        rows: 5
        cols: 50

  - id: NASA_task_load_index_before_tasks
    htmlQuestions:
      - !<Slider>
        text: "How mentally demanding was your previous work or non work-related activities today?"
        elementId: mental_demand
        required: true
        min: 0
        max: 20
        step: 1
        labels:
          min: "Very Low"
          max: "Very High"
      - !<Slider>
        text: "How physically demanding was your previous work or non work-related activities today?"
        elementId: physical_demand
        required: true
        min: 0
        max: 20
        step: 1
        labels:
          min: "Very Low"
          max: "Very High"
      - !<Slider>
        text: "How hurried or rushed was the pace of your previous work or non work-related activities today?"
        elementId: temporal_demand
        required: true
        min: 0
        max: 20
        step: 1
        labels:
          min: "Very Low"
          max: "Very High"
      - !<Slider>
        text: "How successful were you in accomplishing what you were asked to do?"
        elementId: performance
        required: true
        min: 0
        max: 20
        step: 1
        labels:
          min: "Perfect"
          max: "Failure"
      - !<Slider>
        text: "How hard did you have to work to accomplish your level of performance?"
        elementId: effort
        required: true
        min: 0
        max: 20
        step: 1
        labels:
          min: "Very Low"
          max: "Very High"
      - !<Slider>
        text: "How insecure, discouraged, irritated, stressed, and annoyed were you?"
        elementId: frustration
        required: true
        min: 0
        max: 20
        step: 1
        labels:
          min: "Very Low"
          max: "Very High"

  - id: NASA_task_load_index
    htmlQuestions:
      - !<Slider>
        text: "How mentally demanding was the task?"
        elementId: mental_demand
        required: true
        min: 0
        max: 20
        step: 1
        labels:
          min: "Very Low"
          max: "Very High"
      - !<Slider>
        text: "How physically demanding was the task?"
        elementId: physical_demand
        required: true
        min: 0
        max: 20
        step: 1
        labels:
          min: "Very Low"
          max: "Very High"
      - !<Slider>
        text: "How hurried or rushed was the pace of the task?"
        elementId: temporal_demand
        required: true
        min: 0
        max: 20
        step: 1
        labels:
          min: "Very Low"
          max: "Very High"
      - !<Slider>
        text: "How successful were you in accomplishing what you were asked to do?"
        elementId: performance
        required: true
        min: 0
        max: 20
        step: 1
        labels:
          min: "Perfect"
          max: "Failure"
      - !<Slider>
        text: "How hard did you have to work to accomplish your level of performance?"
        elementId: effort
        required: true
        min: 0
        max: 20
        step: 1
        labels:
          min: "Very Low"
          max: "Very High"
      - !<Slider>
        text: "How insecure, discouraged, irritated, stressed, and annoyed were you?"
        elementId: frustration
        required: true
        min: 0
        max: 20
        step: 1
        labels:
          min: "Very Low"
          max: "Very High"

  - id: final_survey
    htmlQuestions:
      - !<Radio>
        text: Single choice question
        elementId: single
        required: true
        info:
          - id: single1
            value: 1
          - id: single2
            value: 2
          - id: single3
            value: 3
